# Generated by Django 5.2.6 on 2025-09-18 08:59

import django.core.validators
import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to=materials.models.material_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('class', 'Class'), ('public', 'Public')], default='private', max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready')], default='uploaded', max_length=16)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
