# Generated by Django 5.2.6 on 2025-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='pdf',
        ),
        migrations.AddField(
            model_name='material',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='public_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='storage_path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
